'use strict';
// Extended features keep the original ledger and storage key intact.
const Base={validate,commit,render,renderHome,renderStats,renderAccounts,renderProfile,transaction,editAccount,action,modal};
const ensure=s=>{for(const k of ['savings','recurring','friends','groups','bills','settlements'])s[k]??=[];s.settings??={theme:'dark',currency:'VND'};return s;};
ensure(state);
validate=function(s){Base.validate(s);ensure(s);for(const k of ['savings','recurring','friends','groups','bills','settlements'])if(!Array.isArray(s[k]))throw Error('Dữ liệu mở rộng không hợp lệ.');
 const ids=new Set(s.accounts.map(a=>a.id));
 for(const r of s.recurring)if(typeof r.id!=='string'||!['day','week','month','year'].includes(r.frequency)||!validDate(r.next)||!ids.has(r.account)||!Number.isSafeInteger(r.amount)||r.amount<=0||!['income','expense'].includes(r.type)||typeof r.name!=='string'||typeof r.category!=='string'||!Number.isInteger(r.anchor)||r.anchor<1||r.anchor>31||typeof r.active!=='boolean')throw Error('Lịch định kỳ không hợp lệ.');
 for(const r of s.savings)if(typeof r.id!=='string'||typeof r.name!=='string'||!Number.isSafeInteger(r.principal)||r.principal<=0||!Number.isFinite(r.rate)||r.rate<0||r.rate>100||!validDate(r.start)||!validDate(r.maturity)||r.maturity<r.start)throw Error('Sổ tiết kiệm không hợp lệ.');
 for(const r of s.friends)if(typeof r.id!=='string'||typeof r.name!=='string')throw Error('Thành viên không hợp lệ.');
 for(const r of s.groups)if(typeof r.id!=='string'||typeof r.name!=='string'||!Array.isArray(r.members)||!r.members.every(m=>m==='me'||s.friends.some(f=>f.id===m)))throw Error('Nhóm không hợp lệ.');
 for(const r of s.bills)if(typeof r.id!=='string'||typeof r.name!=='string'||!Number.isSafeInteger(r.total)||r.total<=0||!Array.isArray(r.shares)||r.shares.reduce((n,x)=>n+x.amount,0)!==r.total||!r.shares.every(x=>Number.isSafeInteger(x.amount)&&x.amount>=0&&typeof x.member==='string')||typeof r.payer!=='string')throw Error('Khoản chia tiền không hợp lệ.');
 for(const r of s.settlements)if(typeof r.from!=='string'||typeof r.to!=='string'||!Number.isSafeInteger(r.amount)||r.amount<=0)throw Error('Khoản trả nợ không hợp lệ.');
 for(const a of s.accounts)if(a.cashback!=null&&(!Number.isFinite(a.cashback)||a.cashback<0||a.cashback>100))throw Error('Tỷ lệ hoàn tiền không hợp lệ.');
 for(const t of s.transactions)if(t.mediaId!=null&&typeof t.mediaId!=='string')throw Error('Video không hợp lệ.');
 if(!['dark','light','system'].includes(s.settings.theme)||!['VND','USD','EUR','JPY'].includes(s.settings.currency))throw Error('Cài đặt không hợp lệ.');
};
let pendingTransaction=null,pendingAccount=null;
commit=function(next){ensure(next);if(pendingTransaction){const p=pendingTransaction;const r=next.transactions.find(t=>p.id?t.id===p.id:!p.before.has(t.id));if(r)Object.assign(r,p.fields);}if(pendingAccount){const p=pendingAccount;const a=next.accounts.find(a=>p.id?a.id===p.id:!p.before.has(a.id));if(a)a.cashback=p.rate;}Base.commit(next);updateNativeWidget();};
function updateNativeWidget(){if(window.webkit?.messageHandlers?.summary){window.webkit.messageHandlers.summary.postMessage({income:sum(state.transactions.filter(t=>t.date===iso()),'income'),expense:sum(state.transactions.filter(t=>t.date===iso()),'expense'),balance:state.accounts.reduce((n,a)=>n+balance(a.id),0),updated:iso()});}}
function applyTheme(){document.documentElement.dataset.theme=state.settings.theme==='system'?(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):state.settings.theme;}
let motionRoute='';
render=function(){ensure(state);applyTheme();Base.render();updateNativeWidget();const route=[page,view,sub,statsMode,selected].join(':');if(route!==motionRoute&&!matchMedia('(prefers-reduced-motion: reduce)').matches){$('#screen').getAnimations?.().forEach(a=>a.cancel());$('#screen').animate?.([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:240,easing:'cubic-bezier(.2,.7,.2,1)'});}motionRoute=route;};
const mutate=fn=>{const next=structuredClone(state);fn(next);commit(next);};
const pname=id=>id==='me'?state.user:state.friends.find(f=>f.id===id)?.name||'Thành viên đã xóa';
const listButton=(text,a)=>btn(text,a,'menu');
const scripts=new Map();
const originalDownload=download;
download=function(name,content,type){originalDownload(name,content,type);const blob=new Blob([content],{type}),url=URL.createObjectURL(blob);const box=$('#formError');if(box){box.textContent='';const a=document.createElement('a');a.href=url;a.download=name;a.textContent='Tệp đã tạo: '+name+' ('+Math.ceil(blob.size/1024)+' KB) — nhấn để tải';box.append(a);}toast('Đã tạo '+name);setTimeout(()=>URL.revokeObjectURL(url),300000);};
function loadScript(file){if(!scripts.has(file))scripts.set(file,new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=file;s.onload=resolve;s.onerror=()=>{scripts.delete(file);reject(Error('Không tải được thư viện. Hãy kết nối mạng và thử lại.'))};document.head.append(s);}));return scripts.get(file);}
async function safe(fn){try{await fn();}catch(e){if($('#formError'))$('#formError').textContent=e.message;toast(e.message);}}
function bind(selector,fn){const el=$(selector);if(el)el.onclick=e=>{e.preventDefault();e.stopPropagation();safe(fn);};}
function manage(title,html){modal(title,html);$('#form').querySelectorAll('button').forEach(b=>b.type='button');}
function optionsPeople(){return [['me',state.user],...state.friends.map(f=>[f.id,f.name])];}
renderHome=function(){Base.renderHome();$('#screen').insertAdjacentHTML('afterbegin',`<div class="quick-pro row"><small class="muted">Sổ thu chi cá nhân</small>${btn('⚡ Quét biên lai','scan','secondary')}</div>`);};
renderProfile=function(){const inc=sum(state.transactions,'income'),exp=sum(state.transactions,'expense');$('#screen').innerHTML=`<div class="card hero"><div class="profile-avatar">${avatarMarkup()}</div><h2>${esc(state.user)}</h2>${btn('Chỉnh sửa hồ sơ','name','link')}</div><h2 class="section">Tổng quan</h2><div class="grid">${[['Giao dịch',state.transactions.length],['Tổng thu nhập',money(inc)],['Tổng chi tiêu',money(exp)],['Số dư',money(state.accounts.reduce((n,a)=>n+balance(a.id),0))]].map(([label,n])=>`<div class="card"><small>${label}</small><strong class="amount">${n}</strong></div>`).join('')}</div><div class="card">${[['Đăng nhập và sổ dùng chung','cloud'],['Bạn bè','friends'],['Nhóm','groups'],['Chia tiền','split'],['Giao dịch định kỳ','recurring'],['Sổ tiết kiệm','savings'],['Cài đặt · Giao diện · Tiền tệ','settings'],['Danh mục tùy chỉnh','categories'],['Xuất PDF / Excel / Sao lưu','reports'],['Hướng dẫn cài ứng dụng','install'],['Ghi chú cá nhân','feedback'],['Chia sẻ ứng dụng','share-app']].filter(([,a])=>a!=='cloud'||!location.hostname.endsWith('.github.io')).map(([l,a])=>listButton(l,a)).join('')}</div><p class="saved-note">CapMoney PWA 2.0 · Tiếng Việt<br>Dữ liệu cá nhân lưu trên thiết bị; sổ dùng chung lưu trên máy chủ bạn cấu hình.</p>`;};
renderAccounts=function(){Base.renderAccounts();if(sub==='accounts'){$('#screen').insertAdjacentHTML('beforeend',`<div class="row section"><h2>Sổ tiết kiệm</h2>${btn('+ Thêm sổ','savings','secondary')}</div>${state.savings.length?state.savings.map(s=>`<div class="card"><strong>${esc(s.name)}</strong><p>${money(s.principal)} · ${s.rate}%/năm</p><small>Lãi ước tính: ${money(Finance.interest(s,iso()))} · Đáo hạn ${esc(s.maturity)}</small></div>`).join(''):empty('Chưa có sổ tiết kiệm','Theo dõi tiền gốc và lãi tích lũy đến ngày đáo hạn.')}<div class="row">${btn('↑↓ Sắp xếp tài khoản','sort-accounts','link')}${btn('Hoàn tiền thẻ','cashback','link')}</div>`);}else if(sub==='investments'){$('#screen').insertAdjacentHTML('beforeend',`<div class="card"><small>Lãi / lỗ danh mục</small><strong class="amount">${money(state.investments.reduce((n,r)=>n+r.current-r.amount,0))}</strong><p class="muted">Sửa từng khoản để cập nhật giá trị nắm giữ.</p></div>`);}};
renderStats=function(){
 Base.renderStats();
 const range=statsRange(),items=state.transactions.filter(t=>t.date>=range.start&&t.date<=range.end&&(account==='all'||t.account===account||t.to===account));
 const expense=sum(items,'expense'),income=sum(items,'income');
 const previous=new Date(range.start+'T12:00:00');
 if(statsMode==='week')previous.setDate(previous.getDate()-7);else if(statsMode==='year')previous.setFullYear(previous.getFullYear()-1);else previous.setMonth(previous.getMonth()-1);
 const before=sum(state.transactions.filter(t=>t.date>=iso(previous)&&t.date<range.start&&(account==='all'||t.account===account||t.to===account)),'expense');
 const buckets=statsMode==='year'?Array.from({length:12},(_,i)=>({label:String(i+1),dates:range.dates.filter(d=>Number(d.slice(5,7))===i+1)})):range.dates.map((d,i)=>({label:statsMode==='week'?['T2','T3','T4','T5','T6','T7','CN'][i]:String(Number(d.slice(8))),dates:[d]}));
 $('#screen').insertAdjacentHTML('beforeend',`<h2 class="section">Phân tích ${statsMode==='week'?'tuần':statsMode==='year'?'năm':'tháng'}</h2><div class="grid"><div class="card"><small>Chi trung bình / ngày</small><strong class="amount">${money(Math.round(expense/range.dates.length))}</strong></div><div class="card"><small>Giao dịch trong kỳ</small><strong class="amount">${items.length}</strong></div><div class="card"><small>So với kỳ trước</small><strong class="amount">${before?((expense-before)/before*100).toFixed(1)+'%':'—'}</strong></div><div class="card"><small>Tỷ lệ giữ lại thu nhập</small><strong class="amount">${income?((income-expense)/income*100).toFixed(1)+'%':'—'}</strong></div></div><h3 class="section">Chi tiêu theo ${statsMode==='year'?'tháng':'ngày'}</h3><div class="daily-chart ${statsMode==='week'?'weekly-chart':''}">${buckets.map(b=>{const n=sum(items.filter(t=>b.dates.includes(t.date)),'expense');return `<div title="${b.dates[0]}: ${money(n)}"><i style="height:${expense?Math.max(1,n/expense*120):1}px"></i><small>${b.label}</small></div>`;}).join('')}</div>${btn('Bản đồ giao dịch','map','secondary full')}`);
};
editAccount=function(id){Base.editAccount(id);const a=state.accounts.find(a=>a.id===id);$('#form').insertAdjacentHTML('afterbegin',field('Hoàn tiền thẻ (% trên khoản chi)','cashback',a?.cashback||0,'number','min="0" max="100" step="0.01"'));const submit=$('#form').onsubmit;$('#form').onsubmit=async e=>{const rate=Number($('#form [name=cashback]').value);if(!Number.isFinite(rate)||rate<0||rate>100){e.preventDefault();$('#formError').textContent='Tỷ lệ hoàn tiền phải từ 0 đến 100%.';return;}pendingAccount={id,before:new Set(state.accounts.map(a=>a.id)),rate};try{await submit(e);}finally{pendingAccount=null;}};};
let activeVideoURL=null;
transaction=function(id,type){Base.transaction(id,type);const t=state.transactions.find(t=>t.id===id);$('#form .form-actions').insertAdjacentHTML('beforebegin',`<div class="card media-controls"><h3>Video 3 giây</h3><video id="clipPreview" playsinline muted controls class="preview-image"></video><div class="row">${btn('Quay 3 giây','record-clip','secondary')}<label>Chọn video<input name="clip" type="file" accept="video/*"></label></div><small id="clipStatus">Tối đa 3 giây, 10 MB. Video lưu riêng trên thiết bị.</small><label><input type="checkbox" name="removeClip"> Bỏ video đã lưu</label></div><fieldset class="location-group"><legend>Địa điểm giao dịch</legend>${btn('Lấy vị trí hiện tại','locate','secondary full')}<p id="locationStatus" class="muted" role="status">Khi nhấn, tọa độ được gửi tới OpenStreetMap để tìm địa chỉ. Bạn vẫn có thể lưu ngay.</p>${select('Địa điểm đã dùng','savedPlace',[['','Chọn địa điểm từ giao dịch cũ'],...recentPlaces().map((t,i)=>[String(i),t.place])],'')}${field('Địa chỉ','place',t?.place||'','text','maxlength="500" autocomplete="off"')}<details><summary>Tọa độ · xem hoặc chỉnh sửa</summary><div class="grid">${field('Vĩ độ','latitude',t?.latitude??'','number','min="-90" max="90" step="any"')}${field('Kinh độ','longitude',t?.longitude??'','number','min="-180" max="180" step="any"')}</div></details><small>Địa chỉ gần nhất · <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap</a></small></fieldset>`);
 let clip=null;const attach=async blob=>{if(blob.size>10*1024*1024)throw Error('Video vượt quá 10 MB.');clip=blob;if(activeVideoURL)URL.revokeObjectURL(activeVideoURL);activeVideoURL=URL.createObjectURL(blob);$('#clipPreview').src=activeVideoURL;$('#clipStatus').textContent='Video sẵn sàng. Nhấn Lưu để đính kèm.';};
 if(t?.mediaId)MediaStore.get(t.mediaId).then(blob=>{if(blob&&$('#clipPreview')){activeVideoURL=URL.createObjectURL(blob);$('#clipPreview').src=activeVideoURL;}}).catch(()=>toast('Không đọc được video.'));
 bind('[data-action=record-clip]',async()=>{const b=$('[data-action=record-clip]');b.disabled=true;$('#clipStatus').textContent='Đang quay…';try{await attach(await MediaStore.record($('#clipPreview')));}finally{b.disabled=false;}});
 $('#form [name=clip]').onchange=e=>safe(async()=>{const f=e.target.files[0];if(!f)return;const duration=await MediaStore.duration(f);if(!Number.isFinite(duration)||duration>3.25)throw Error('Chọn video dài tối đa 3 giây.');await attach(f);});
 bindLocation();
 $('#form [name=savedPlace]').onchange=e=>{const t=recentPlaces()[Number(e.target.value)];if(e.target.value===''||!t)return;$('#form [name=place]').value=t.place;$('#form [name=latitude]').value=t.latitude??'';$('#form [name=longitude]').value=t.longitude??'';$('#locationStatus').textContent='Đã chọn địa điểm từ giao dịch cũ; không cần chờ GPS.';};
 const submit=$('#form').onsubmit;$('#form').onsubmit=async e=>{e.preventDefault();const place=$('#form [name=place]').value,lat=$('#form [name=latitude]').value,lng=$('#form [name=longitude]').value,remove=$('#form [name=removeClip]').checked;const prior=new Set(state.transactions.map(t=>t.id));let mediaId=t?.mediaId;try{if((lat===''&&lng!=='')||(lat!==''&&lng==='')||lat!==''&&(!Number.isFinite(Number(lat))||Math.abs(Number(lat))>90||!Number.isFinite(Number(lng))||Math.abs(Number(lng))>180))throw Error('Tọa độ không hợp lệ.');if(clip){mediaId=uid();await MediaStore.put(mediaId,clip);}pendingTransaction={id,before:prior,fields:{mediaId:remove?null:mediaId,place,latitude:lat===''?null:Number(lat),longitude:lng===''?null:Number(lng)}};try{await submit(e);}finally{pendingTransaction=null;}if($('#dialog').open){if(clip)await MediaStore.delete(mediaId);return;}render();}catch(err){toast(err.message);}};
};
function savings(){manage('Sổ tiết kiệm',`${btn('+ Thêm sổ','new-saving','primary full')}${state.savings.map(s=>`<button class="menu" data-saving="${esc(s.id)}"><span>${esc(s.name)}<small class="block">${money(s.principal)} · ${s.rate}%/năm</small></span><strong>${money(Finance.interest(s,iso()))}</strong></button>`).join('')}<p class="muted">Ước tính lãi đơn theo số ngày thực tế/365, chưa khấu trừ thuế/phí. Sổ này theo dõi riêng, không tự thay đổi số dư tài khoản.</p>`);bind('[data-action=new-saving]',()=>editSaving());$('#form').querySelectorAll('[data-saving]').forEach(b=>b.onclick=()=>editSaving(b.dataset.saving));}
function editSaving(id){const r=state.savings.find(s=>s.id===id)||{name:'',principal:'',rate:5,start:iso(),maturity:Finance.advance(iso(),'year')};modal('Thông tin sổ tiết kiệm',field('Tên sổ','name',r.name,'text','required maxlength="80"')+field('Tiền gốc (VND)','principal',r.principal,'number','required min="1"')+field('Lãi suất (%/năm)','rate',r.rate,'number','required min="0" max="100" step="0.01"')+field('Ngày gửi','start',r.start,'date','required')+field('Ngày đáo hạn','maturity',r.maturity,'date','required')+(id?btn('Xóa sổ','delete-saving','danger full'):''),f=>mutate(s=>{const v={id:id||uid(),name:f.get('name').trim(),principal:amount(f.get('principal')),rate:Number(f.get('rate')),start:f.get('start'),maturity:f.get('maturity')};const i=s.savings.findIndex(s=>s.id===id);if(i<0)s.savings.push(v);else s.savings[i]=v;}));bind('[data-action=delete-saving]',()=>removeRecord('savings',id,'Xóa sổ tiết kiệm?'));}
function recurring(){manage('Giao dịch định kỳ',`${btn('+ Tạo lịch','new-recurring','primary full')}${state.recurring.map(r=>`<button class="menu" data-recurring="${esc(r.id)}"><span>${esc(r.name)}<small class="block">${r.active?'Lần tới: '+r.next:'Đã tạm dừng'}</small></span><strong>${money(r.amount)}</strong></button>`).join('')}<p class="muted">Các giao dịch đến hạn được ghi khi mở ứng dụng. Không tự chuyển tiền ngân hàng.</p>${btn('Ghi các khoản đến hạn','process-recurring','secondary full')}`);bind('[data-action=new-recurring]',()=>editRecurring());bind('[data-action=process-recurring]',()=>{processRecurring();recurring()});$('#form').querySelectorAll('[data-recurring]').forEach(b=>b.onclick=()=>editRecurring(b.dataset.recurring));}
function processRecurring(){if(locked)return;const result=Finance.due(state,iso());if(result.count){commit(result.state);toast('Đã ghi '+result.count+' giao dịch định kỳ.');render();}}
function editRecurring(id){const r=state.recurring.find(r=>r.id===id)||{name:'',type:'expense',amount:'',account:state.accounts[0].id,category:state.categories[0],frequency:'month',next:iso(),active:true};modal('Lịch thu chi',field('Tên / ghi chú','name',r.name,'text','required maxlength="100"')+select('Loại','type',[['expense','Chi'],['income','Thu']],r.type)+field('Số tiền (VND)','amount',r.amount,'number','required min="1"')+select('Tài khoản','account',state.accounts.map(a=>[a.id,a.name]),r.account)+select('Danh mục','category',state.categories,r.category)+select('Lặp lại','frequency',[['day','Hằng ngày'],['week','Hằng tuần'],['month','Hằng tháng'],['year','Hằng năm']],r.frequency)+field('Lần tiếp theo','next',r.next,'date','required')+select('Trạng thái','active',[['true','Hoạt động'],['false','Tạm dừng']],String(r.active))+(id?btn('Xóa lịch','delete-recurring','danger full'):''),f=>mutate(s=>{const v={id:id||uid(),name:f.get('name').trim(),type:f.get('type'),amount:amount(f.get('amount')),account:f.get('account'),category:f.get('category'),frequency:f.get('frequency'),next:f.get('next'),anchor:Number(f.get('next').slice(8)),active:f.get('active')==='true'};const i=s.recurring.findIndex(r=>r.id===id);if(i<0)s.recurring.push(v);else s.recurring[i]=v;}));bind('[data-action=delete-recurring]',()=>removeRecord('recurring',id,'Xóa lịch? Giao dịch đã ghi vẫn được giữ.'));}
function friends(){manage('Bạn bè',`${btn('+ Thêm người','new-friend','primary full')}${state.friends.map(f=>`<button class="menu" data-friend="${esc(f.id)}">${esc(f.name)} <span>›</span></button>`).join('')}<p class="muted">Danh sách này dùng để chia tiền. Để cùng ghi sổ trên các thiết bị, mở “Đăng nhập và sổ dùng chung”.</p>`);bind('[data-action=new-friend]',()=>editFriend());$('#form').querySelectorAll('[data-friend]').forEach(b=>b.onclick=()=>editFriend(b.dataset.friend));}
function editFriend(id){const f=state.friends.find(f=>f.id===id);modal('Thành viên',field('Tên','name',f?.name||'','text','required maxlength="60"'),d=>mutate(s=>{const name=d.get('name').trim();if(!name)throw Error('Nhập tên.');if(id)s.friends.find(f=>f.id===id).name=name;else s.friends.push({id:uid(),name});}));}
function groups(){manage('Nhóm chia tiền',`${btn('+ Tạo nhóm','new-group','primary full')}${state.groups.map(g=>`<button class="menu" data-group="${esc(g.id)}">${esc(g.name)} <small>${g.members.length} người</small></button>`).join('')}`);bind('[data-action=new-group]',()=>editGroup());$('#form').querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>editGroup(b.dataset.group));}
function editGroup(id){const g=state.groups.find(g=>g.id===id);modal('Nhóm',field('Tên nhóm','name',g?.name||'','text','required maxlength="60"')+optionsPeople().map(([id,name])=>`<label><input type="checkbox" name="members" value="${esc(id)}" ${g?.members.includes(id)||id==='me'?'checked':''}>${esc(name)}</label>`).join(''),f=>mutate(s=>{const name=f.get('name').trim(),members=f.getAll('members');if(!name||members.length<2)throw Error('Nhập tên và chọn ít nhất 2 người.');const r={id:id||uid(),name,members};const i=s.groups.findIndex(g=>g.id===id);if(i<0)s.groups.push(r);else s.groups[i]=r;}));}
function split(){const debt=Finance.settlements(state.bills,state.settlements);manage('Chia tiền',`${btn('+ Thêm khoản chia','new-bill','primary full')}<h3 class="section">Cần thanh toán</h3>${debt.length?debt.map((d,i)=>`<div class="card"><p>${esc(pname(d.from))} → ${esc(pname(d.to))}</p><strong>${money(d.amount)}</strong><button class="link" data-settle="${i}">Đánh dấu đã trả</button></div>`).join(''):'<p class="income">Đã cân bằng các khoản chia.</p>'}<h3 class="section">Các khoản đã chia</h3>${state.bills.map(b=>`<button class="menu" data-bill="${esc(b.id)}"><span>${esc(b.name)}<small class="block">${esc(pname(b.payer))} đã trả</small></span><strong>${money(b.total)}</strong></button>`).join('')}<p class="muted">Chia tiền theo dõi riêng; không tự cộng/trừ sổ thu chi cá nhân.</p>`);bind('[data-action=new-bill]',()=>editBill());$('#form').querySelectorAll('[data-settle]').forEach(b=>b.onclick=()=>{const d=debt[Number(b.dataset.settle)];modal('Xác nhận đã thanh toán',`<p>${esc(pname(d.from))} đã trả ${money(d.amount)} cho ${esc(pname(d.to))}?</p>`,()=>mutate(s=>s.settlements.push({...d,id:uid(),date:iso()})));});$('#form').querySelectorAll('[data-bill]').forEach(b=>b.onclick=()=>editBill(b.dataset.bill));}
function editBill(id){const b=state.bills.find(b=>b.id===id);modal('Khoản chia tiền',field('Nội dung','name',b?.name||'','text','required maxlength="100"')+field('Tổng tiền (VND)','total',b?.total||'','number','required min="1"')+select('Người đã trả','payer',optionsPeople(),b?.payer||'me')+select('Chọn nhanh nhóm','group',[['','Chọn thủ công'],...state.groups.map(g=>[g.id,g.name])],'')+'<h3>Người tham gia (chia đều)</h3>'+optionsPeople().map(([id,name])=>`<label><input type="checkbox" name="members" value="${esc(id)}" ${!b||b.shares.some(s=>s.member===id)?'checked':''}>${esc(name)}</label>`).join(''),f=>mutate(s=>{const total=amount(f.get('total')),members=f.getAll('members'),payer=f.get('payer');if(!members.includes(payer))throw Error('Người trả phải nằm trong nhóm tham gia.');const r={id:id||uid(),name:f.get('name').trim(),total,payer,shares:Finance.split(total,members)};const i=s.bills.findIndex(b=>b.id===id);if(i<0)s.bills.push(r);else s.bills[i]=r;}));$('#form [name=group]').onchange=e=>{const group=state.groups.find(g=>g.id===e.target.value);if(group)$('#form').querySelectorAll('[name=members]').forEach(c=>c.checked=group.members.includes(c.value));};}
function cashback(){const lines=state.accounts.filter(a=>a.cashback>0).map(a=>{const spent=sum(state.transactions.filter(t=>t.account===a.id&&t.date.startsWith(month)),'expense');return `<div class="card"><strong>${esc(a.name)} · ${a.cashback}%</strong><p>Chi tháng ${month}: ${money(spent)}</p><strong class="income">Hoàn tiền dự tính: ${money(Math.round(spent*a.cashback/100))}</strong></div>`});manage('Hoàn tiền thẻ',period()+(lines.join('')||'<p>Chỉnh sửa tài khoản và nhập tỷ lệ hoàn tiền để theo dõi.</p>')+'<p class="muted">Ước tính theo tỷ lệ chung, chưa áp dụng trần hoặc điều kiện của ngân hàng. Khi nhận tiền thực tế, ghi một giao dịch Thu.</p>');}
function settings(){modal('Cài đặt',select('Giao diện','theme',[['dark','Tối'],['light','Sáng'],['system','Theo thiết bị']],state.settings.theme)+select('Tiền tệ hiển thị báo cáo quy đổi','currency',['VND','USD','EUR','JPY'],state.settings.currency)+field('1 đơn vị ngoại tệ bằng bao nhiêu VND','rate',state.settings.rate||1,'number','min="0.000001" step="any" required')+'<p class="muted">Sổ gốc luôn ghi bằng VND. Tỷ giá do bạn nhập chỉ dùng để xem báo cáo quy đổi, không sửa số tiền lịch sử.</p><p>Ngôn ngữ: Tiếng Việt</p>',f=>mutate(s=>{const rate=Number(f.get('rate'));if(!Number.isFinite(rate)||rate<=0)throw Error('Tỷ giá không hợp lệ.');s.settings={...s.settings,theme:f.get('theme'),currency:f.get('currency'),rate};}));}
function categories(){manage('Danh mục tùy chỉnh',`${btn('+ Thêm danh mục','new-category','primary full')}${state.categories.map((c,i)=>`<button class="menu" data-category="${i}">${esc(c)} <span>✎</span></button>`).join('')}`);bind('[data-action=new-category]',()=>Base.action('categories'));$('#form').querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{const old=state.categories[Number(b.dataset.category)];modal('Đổi tên danh mục',field('Tên mới','name',old,'text','required maxlength="40"'),f=>mutate(s=>{const name=f.get('name').trim();if(!name||name!==old&&s.categories.includes(name))throw Error('Tên trống hoặc trùng danh mục.');s.categories[s.categories.indexOf(old)]=name;for(const t of s.transactions)if(t.category===old)t.category=name;for(const r of s.recurring)if(r.category===old)r.category=name;for(const b of s.budgets)if(b.category===old)b.category=name;}));});}
async function scan(){manage('Quét biên lai',`<label>Chọn ảnh biên lai<input id="receiptFile" type="file" accept="image/*"></label>${btn('Nhận diện chữ trên ảnh','ocr','primary full')}<p id="ocrStatus" class="muted">Ảnh được xử lý trên thiết bị. Kiểm tra lại số tiền trước khi lưu.</p><label>Hoặc dán chữ từ biên lai<textarea id="receiptText" rows="6"></textarea></label>${btn('Tạo giao dịch từ nội dung','parse-receipt','secondary full')}${btn('Hướng dẫn Shortcut Double Tap','shortcut-help','link full')}`);bind('[data-action=ocr]',async()=>{const file=$('#receiptFile').files[0];if(!file)throw Error('Chọn ảnh biên lai.');await loadScript('vendor/tesseract.min.js');const b=$('[data-action=ocr]');b.disabled=true;let worker;try{worker=await Tesseract.createWorker(['vie','eng'],1,{workerPath:new URL('vendor/worker.min.js',location.href).href,corePath:new URL('vendor/tesseract-core-lstm.wasm.js',location.href).href,langPath:new URL('vendor/',location.href).href,gzip:false,logger:m=>{if($('#ocrStatus'))$('#ocrStatus').textContent=m.status+' '+Math.round((m.progress||0)*100)+'%';}});const r=await worker.recognize(file);$('#receiptText').value=r.data.text;$('#ocrStatus').textContent='Đã đọc xong. Kiểm tra nội dung và tạo giao dịch.';}finally{if(worker)await worker.terminate();b.disabled=false;}});bind('[data-action=parse-receipt]',()=>{const r=Finance.parseReceipt($('#receiptText').value);transaction();$('#form [name=amount]').value=r.amount||'';$('#form [name=note]').value=r.note;});bind('[data-action=shortcut-help]',()=>manage('Shortcut Double Tap','<p>Tạo phím tắt trên iPhone gồm: Chụp ảnh màn hình → Trích xuất văn bản từ ảnh → Mã hóa URL văn bản → Mở URL bên dưới, thay TEXT bằng kết quả đã mã hóa.</p><code>'+esc(new URL('./',location.href).href)+'?receipt=TEXT</code><p>Sau đó gán phím tắt vào Chạm vào mặt sau trong cài đặt Trợ năng của iPhone. CapMoney sẽ điền sẵn giao dịch để bạn kiểm tra và lưu.</p>'));}
function map(){const items=filtered().filter(t=>Number.isFinite(t.latitude)&&Number.isFinite(t.longitude));manage('Bản đồ giao dịch',items.length?items.map(t=>`<div class="card"><strong>${esc(t.place||t.note||t.category)}</strong><p>${money(t.amount)} · ${esc(t.date)}</p><a target="_blank" rel="noopener noreferrer" href="https://www.openstreetmap.org/?mlat=${t.latitude}&mlon=${t.longitude}#map=16/${t.latitude}/${t.longitude}">Xem vị trí trên bản đồ</a></div>`).join(''):'<p>Chưa có giao dịch gắn vị trí trong tháng. Thêm tọa độ khi chỉnh sửa giao dịch.</p>');}
function reportRows(){return filtered().map(t=>[t.date,{income:'Thu',expense:'Chi',transfer:'Chuyển tiền'}[t.type],t.amount,accountName(t.account),t.type==='transfer'?accountName(t.to):'',t.category,t.note]);}
async function exportExcel(){await loadScript('vendor/exceljs.min.js');const book=new ExcelJS.Workbook();book.creator='CapMoney';const sheet=book.addWorksheet('Giao dịch');sheet.addRow(['Ngày','Loại','Số tiền VND','Tài khoản','Tài khoản nhận','Danh mục','Ghi chú']);reportRows().forEach(row=>sheet.addRow(row));sheet.columns.forEach((c,i)=>c.width=i===6?45:23);sheet.getColumn(3).numFmt='#,##0';sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF355D84'}};sheet.views=[{state:'frozen',ySplit:1}];sheet.autoFilter='A1:G1';download(`CapMoney-${month}.xlsx`,await book.xlsx.writeBuffer(),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}
async function exportPDF(){await loadScript('vendor/pdf-lib.min.js');await loadScript('vendor/fontkit.umd.min.js');const pdf=await PDFLib.PDFDocument.create();pdf.registerFontkit(fontkit);const font=await pdf.embedFont(await (await fetch('vendor/NotoSans-Regular.ttf')).arrayBuffer(),{subset:true});let p,y;const newPage=()=>{p=pdf.addPage([595.28,841.89]);y=795;};newPage();const line=(text,size=11)=>{const words=String(text).split(/\s+/);let row='';for(const w of words){if(font.widthOfTextAtSize(row+' '+w,size)>500&&row){if(y<50)newPage();p.drawText(row,{x:45,y,size,font});y-=19;row=w;}else row+=(row?' ':'')+w;}if(y<50)newPage();p.drawText(row,{x:45,y,size,font});y-=22;};line('CapMoney · Báo cáo thu chi',20);line('Tháng '+month+' · '+(account==='all'?'Tất cả tài khoản':accountName(account)));line('Thu: '+money(sum(filtered(),'income'))+'   Chi: '+money(sum(filtered(),'expense')));line('');for(const r of reportRows()){line(`${r[0]} | ${r[1]} | ${new Intl.NumberFormat('vi-VN').format(r[2])} VND`);line(`${r[3]}${r[4]?' → '+r[4]:''} · ${r[5]} · ${r[6]}`);y-=5;}download(`CapMoney-${month}.pdf`,await pdf.save(),'application/pdf');}
async function backup(){const media={};for(const t of state.transactions){if(t.mediaId&&!media[t.mediaId]){const blob=await MediaStore.get(t.mediaId);if(blob)media[t.mediaId]=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob);});}}download('CapMoney-backup-'+iso()+'.json',JSON.stringify({format:'capmoney-complete-1',state,media}),'application/json');}
async function restoreBundle(bundle){
 const complete=bundle?.format==='capmoney-complete-1';
 const next=structuredClone(complete?bundle.state:bundle);
 validate(next);
 const media=complete?bundle.media||{}:{};
 if(typeof media!=='object'||Array.isArray(media))throw Error('Kho video sao lưu không hợp lệ.');
 const staged=[],mapping=new Map();
 for(const t of next.transactions){
  if(!t.mediaId||mapping.has(t.mediaId))continue;
  const oldId=t.mediaId;
  if(!Object.hasOwn(media,oldId)){
   if(!complete&&await MediaStore.get(oldId)){mapping.set(oldId,oldId);continue;}
   throw Error('Bản sao lưu thiếu video đính kèm. Hãy chọn bản sao lưu đầy đủ.');
  }
  const data=media[oldId];
  if(typeof data!=='string'||!/^data:video\/(mp4|webm|quicktime);base64,/.test(data))throw Error('Video sao lưu không hợp lệ.');
  const blob=await (await fetch(data)).blob();
  if(!blob.size||blob.size>10*1024*1024)throw Error('Video vượt giới hạn hoặc rỗng.');
  const newId=uid();mapping.set(oldId,newId);staged.push([newId,blob]);
 }
 for(const t of next.transactions)if(t.mediaId)t.mediaId=mapping.get(t.mediaId);
 const written=[],was=locked;
 try{
  for(const [id,blob] of staged){written.push(id);await MediaStore.put(id,blob);}
  locked=false;commit(next);
 }catch(error){
  locked=was;
  await Promise.allSettled(written.map(id=>MediaStore.delete(id)));
  throw error;
 }
 account='all';$('#notice').hidden=true;
}
function restore(){modal('Khôi phục toàn bộ dữ liệu','<label>Bản sao lưu JSON<input name="file" type="file" accept=".json" required></label><label><input type="checkbox" required> Đồng ý thay thế sổ hiện tại bằng bản sao lưu</label>',async f=>{
 const file=f.get('file');if(file.size>250*1024*1024)throw Error('Bản sao lưu quá lớn (tối đa 250 MB).');
 await restoreBundle(JSON.parse(await file.text()));
});}
function reports(){manage('Xuất báo cáo',`<p>Phạm vi: tháng ${month}, ${esc(account==='all'?'tất cả tài khoản':accountName(account))}.</p>${listButton('Tải PDF','pdf')}${listButton('Tải Excel (.xlsx)','xlsx')}${listButton('Tải CSV','csv')}${listButton('Sao lưu toàn bộ, kèm video','backup-full')}${listButton('Khôi phục bản sao lưu','restore-full')}<p>Quy đổi tham khảo: ${new Intl.NumberFormat('vi-VN',{style:'currency',currency:state.settings.currency}).format((sum(filtered(),'income')-sum(filtered(),'expense'))/(state.settings.currency==='VND'?1:state.settings.rate||1))}</p>`);}
action=function(name){const actions={'savings':savings,'recurring':recurring,'friends':friends,'groups':groups,'split':split,'settings':settings,'categories':categories,'cashback':cashback,'scan':scan,'map':map,'reports':reports,'xlsx':exportExcel,'pdf':exportPDF,'backup-full':backup,'restore-full':restore,'export':backup,'import':restore,'sort-accounts':()=>{mutate(s=>s.accounts.sort((a,b)=>a.name.localeCompare(b.name,'vi')));render()},'widget':()=>manage('Widget iPhone','<p>Widget hệ thống cần ứng dụng iOS và phần mở rộng WidgetKit. Bộ mã iOS đi kèm dự án kết nối số liệu từ CapMoney với widget; cần biên dịch và ký ứng dụng trên máy Mac.</p><p>PWA trong Safari không tự cài được widget WidgetKit.</p>'),'pro-status':()=>manage('CapMoney Pro','<p>Đã mở không giới hạn giao dịch, tài khoản, ngân sách và danh mục.</p><p>Đã có sổ tiết kiệm, hoàn tiền ước tính, nhóm chia tiền, định kỳ, OCR, video, PDF/Excel. Sổ dùng chung chạy qua máy chủ đi kèm.</p><p>Đăng nhập Apple cần cấu hình Apple Developer. Widget hệ thống cần xây dựng ứng dụng iOS đi kèm.</p>'),'feedback':()=>modal('Ghi chú cá nhân',`<label>Nội dung<textarea name="text" rows="6">${esc(state.settings.feedback||'')}</textarea></label><p class="muted">Lưu ghi chú tại thiết bị, không gửi đi.</p>`,f=>mutate(s=>s.settings.feedback=f.get('text'))),'share-app':async()=>{const url=new URL('./',location.href).href;if(navigator.share)await navigator.share({title:'CapMoney',url});else manage('Chia sẻ ứng dụng','<p>Sao chép địa chỉ này:</p><code>'+esc(url)+'</code>');}};if(actions[name])return safe(actions[name]);if(name==='roadmap')return action('pro-status');return Base.action(name);};
$('#dialog').addEventListener('close',()=>{if(activeVideoURL){URL.revokeObjectURL(activeVideoURL);activeVideoURL=null;}});
try{validate(state);render();processRecurring();const receipt=new URLSearchParams(location.search).get('receipt');if(receipt){const r=Finance.parseReceipt(receipt);transaction();$('#form [name=amount]').value=r.amount||'';$('#form [name=note]').value=r.note;history.replaceState(null,'',location.pathname);}}catch(e){toast(e.message);}
